select * from customer_info limit 10;

-- Q1) What is the total revenue generated by male vs. female customer?
select gender, sum(purchase_amount) as revenue 
from customer_info
group by gender

-- Q2) Which customers used s discount but still spent more than the average purchase amount?
select customer_id, purchase_amount 
from customer_info 
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer_info)

-- Q3) Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating" 
from customer_info
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q4) Compare the average Purchase Amount between standard and express shipping.
select shipping_type, round(avg(purchase_amount),2)
from customer_info
where shipping_type in ('Standard', 'Express')
group by shipping_type;

-- Q5) Do Subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status, 
count(customer_id) as Total_customers, 
sum(purchase_amount) as Total_Revenue, 
round(avg(purchase_amount),2) as Average_Spend
from customer_info
group by subscription_status;

-- Q6) Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
ROUND(AVG(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100, 2) AS discount_percentage
FROM customer_info
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- Q7) Segment customers into new, returning, and loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as (
select customer_id, previous_purchases,
CASE 
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer_info
)

select customer_segment, count(*) as "Number_Of_Customers"
from customer_type
group by customer_segment;

-- Q8) What are the top 3 most purchased products within each category?
with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer_info
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <=3;

-- Q9) Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, 
count(customer_id) as repeat_buyers 
from customer_info
where previous_purchases > 5
group by subscription_status

-- Q10) What is the revenue contribution of each age group?
select age_group, 
sum(purchase_amount) as total_revenue
from customer_info
group by age_group
order by total_revenue desc;